### PR TITLE
Dequip > Unequip

### PR DESCRIPTION
**Pull request by Enverex**
Switch to a real word.

### CODE REVIEW

**Comment by Nammi-namm** [comment]
You missed         `"Hints.Sundial.Dequip": "Drop the equipped tool by choosing Dequip in your Context Menu.",`

**Comment by ProbablePrime** [comment]
Both Dequip and UnEquip are not in many dictionaries. I think "un-equip" would be most correct english wise. But we'll leave this PR open while we work on other matters and think about it some more.

**Comment by Enverex** [comment]
De-equip (with or without hyphen) just doesn't really seem to exist in any way, shape or form anywhere. While unequip doesn't exist in British English dictionaries, it's been an accepted standard for "take off item" for a while. Examples:

https://en.wiktionary.org/wiki/unequip
```    (transitive) To remove equipment from.     (transitive, video games) In role-playing video games, to deactivate (an item carried by a player).```

https://www.yourdictionary.com/unequip
```(video games) In role-playing video games, to [deactivate] an item being carried by a player.```

https://www.wordgamedictionary.com/dictionary/word/unequip/
```1. In role-playing video games, to deactivate an item being carried by a player.  2. To remove equipment.```

Seems like it would make sense to use a somewhat commonly accepted term than to use one that doesn't seem to be in use anywhere and would be less understood.

**Comment by Frooxius** [comment]
Thanks for the info, I'll merge this in!

**Pull request merged**
