### PR TITLE
Updated de.json, Removed legacy keys, added missing keys

### PR DESCRIPTION
**Pull request by JackTheFoxOtter**
Brought the German translation on-par with the current English one. Removed a bunch of legacy stuff and added translations for all missing keys. Sorry for the massive PR but this includes all changes I had already laying around locally that didn't make it into the current version yet. Feedback / Corrections are appreciated!

### CODE REVIEW

**Comment by Alex-2Pi** [comment]
I understand that all keys that are not in en must be deleted?

**Comment by JackTheFoxOtter** [comment]
@Alex-2Pi pretty much, yeah. The current version of this PR is in parity with current version of en.json

**Comment by JackTheFoxOtter** [comment]
@ProbablePrime conflicting PRs are closed, should be good to merge now :)

**Comment by ProbablePrime** [comment]
Removing conflict as per conversation, this is ready to go now.

**Comment by Frooxius** [comment]
Thank you very much for the contributions, merging this in!

**Pull request merged**
