### PR TITLE
Hungarian (hu-HU)

### PR DESCRIPTION
**Pull request by fernzhn**
It took me a long time, but I've only managed to translate the Steam page as best as I could. Hopefully, soon, I will be able to start translating the program itself! If I did something wrong, please tell me! as, I am new to Github!

### CODE REVIEW

**Comment by fernzhn** [comment]
translated 2fa, main menu, login/register page initially
also, closed #399 due to it being a duplicate

**Comment by Frooxius** [comment]
Thank you so much for the translations! I always get excited when we get a new language!

However there's one major thing with the current PR on why I can't merge this - the Hungarian file has lots of strings in English. Those should not be included, the locale should always include lines only in the language it's for! 

Any untranslated strings need to be left out.

**Comment by fernzhn** [comment]
I will fix this error real quick.

Does the line number need to match with the original file?

**Comment by Frooxius** [comment]
No the line numbers are irrelevant.

**Comment by fernzhn** [comment]
Okay, thank you for your answer. I'll work on the file.

**Comment by fernzhn** [comment]
untranslated strings are now deleted! 🫡

**Comment by Frooxius** [comment]
Unfortunately the JSON is invalid now! It seems there's a missing/extra double quote?

**Comment by fernzhn** [comment]
> Unfortunately the JSON is invalid now! It seems there's a missing/extra double quote?

The one comma (,) at the very end of the last line caused the error. The site I've just checked the code with said the json file is now valid. My apologies for the inconvenience. 😅

**Comment by Frooxius** [comment]
Thank you very much, merging!

**Pull request merged**
