### PR TITLE
Updates Wizard.* and Tools.Names.* for EO

### PR DESCRIPTION
**Pull request by RobertBaruch**
The changes in this file are independent of [PR#11](https://github.com/Yellow-Dog-Man/Locale/pull/11). Please merge PR#11 first. After that is merged, I will rebase this change for final submit,

### CODE REVIEW

**Comment by Jackalgirl** [comment]
My updates for "Importer", "Exporter", "NewWorld", and "FullBody" are done, but I'm holding off on committing them until I can confirm that they don't cause any major issues in Resonite.  However, I can't do that until the issue I'm having with instacrashing upon load (Windows 11, Steam) is resolved (it's not the eo.json file that's doing it).

**Comment by RobertBaruch** [comment]
There's time -- I'm sure everyone is busy preparing for the big release!

**Comment by Frooxius** [comment]
I'm waiting on this one if you want to rebase. I'd recommend keeping this as Draft if you don't want them to be merged right away.

**Comment by RobertBaruch** [comment]
Synced!

**Comment by RobertBaruch** [comment]
Converted to draft so that we only have one pull request non-draft for eo.json.

**Comment by Jackalgirl** [comment]
I'm going to leave my draft in draft status until yours is done, Robert. : )

**Comment by RobertBaruch** [comment]
Synced and ready for merge.

**Comment by Frooxius** [comment]
Thank you, merging this!

**Pull request merged**
