### PR TITLE
KR:Intergrations, GiggleTech, Favorates, Notify..

### PR DESCRIPTION
**Pull request by mirpasec**

### CODE REVIEW

**Comment by shadowpanther** [comment]
Hey, @mirpasec, you changed other language files as part of your PR, but that would cause conflicts in others' PRs. Please don't do this. My https://github.com/Yellow-Dog-Man/Locale/pull/331 already addresses this key name change in a better way.

Last time someone did that, my PR was not accepted at all, and I had to do a manual merge to fix the conflict properly.

You don't have to get a green checkmark for your PR to get accepted. Please don't try to fix everything at once.

**Comment by Frooxius** [comment]
This has conflicts with the ja and ko locales right now.

**Comment by Frooxius** [comment]
Some of the conflicts are for the same strings in Korean language that I can tell. Since I don't understand the language, I cannot resolve these on my end.

Are you able to resolve them on yours please?

**Comment by mirpasec** [comment]
I checked it now because I was focused on realistic matters. sorry. Deleted keys for other languages were restored, and duplicate Korean keys were corrected.
(Google translation)

**Comment by Frooxius** [comment]
Ah awesome, thank you very much! Merging in!

**Pull request merged**
