### PR TITLE
Add strings for FOV Effect setting

### PR DESCRIPTION
**Pull request by ProbablePrime**
See: https://github.com/Yellow-Dog-Man/FrooxEngine/pull/755
and: https://youtu.be/Z89xbYd6w4w

### CODE REVIEW

**Comment by ELO621B73** [comment]
Beat me to it :(

**Comment by AmasterAmaster** [comment]
its not a race XD XD XD

**Comment by ELO621B73** [comment]
> its not a race XD XD XD

But what If I want to be useful?

**Comment by ELO621B73** [comment]
Also wouldn't this fall under "Accessibility settings" and or the "Low motion" mode?

mentioned before?

**Comment by ProbablePrime** [comment]
When it comes to new strings, the team are going to be the ones adding them. This is needed because everything that is WIP is exactly that a WIP. For example you can see that from the video posted earlier today to now, i've changed the name of the setting. 

This occurred when I wrote the locale strings for it.

So, please wait for the feature to be fully complete before trying to do any form of localization. This is covered in our readme:

> DON'T Submit strings from PRs that have the "New Strings" label until that PR is merged. The development team may need to update or change these strings as a part of their inclusion and this can cause conflicts. Wait till the PR is merged and THEN work on the new strings.

Secondly, in relation to low motion mode. Yes this is a part of low motion mode.

As described a few times at office hours, Low Motion mode is going to need to override a bunch of settings when it is swapped on. For example the Dash's Animation would be slowed down, and perhaps the particles would need to be disabled.

Its going to work like(functional description, have not thought about this technically), "presets" where when you enable a setting it automatically sets a bunch of other settings to those values. 

I also want to "lock" those settings, so you have to turn off low motion mode when you want to change them.

These locks would then visually be represented(not sure how, havent thought about it). My first naive idea is to emulate the "some settings are managed by your organization" thing:
image

That feature would also resolve https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2340.

Please continue discussion in https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/554

**Comment by ELO621B73** [comment]
Oh alright, I just heard people discussing the "Low Motion" mode and didn't know that it was a planned thing.

Also Sorry about potentially causing issues making a PR I didn't catch that part of the readme. (My bad)

**Comment by ProbablePrime** [comment]
No worries, thank you for trying to contribute regardless :D

**Comment by Frooxius** [comment]
Merging in!

**Pull request merged**
