### PR TITLE
feat(privacy): rich presence settings

### PR DESCRIPTION
**Pull request by ProbablePrime**

### CODE REVIEW

**Comment by Muppeq** [comment]
Hi, you still have a leftover 'Discord' in the Steam Rich Presence description.

**Comment by ProbablePrime** [comment]
As per our Dos and Don'ts: https://github.com/Yellow-Dog-Man/Locale#dos-and-donts

Translators, Please don't work on these strings until this PR is merged. It was a little difficult to adjust the existing strings into the new ones. So let's wait for it all to be confirmed.

**Comment by Frooxius** [comment]
Merging this in now! Thanks!

**Comment by ProbablePrime** [comment]
Translators, Feel free to translate these now these are merged!

**Pull request merged**
