### PR TITLE
Fixing some missing locale strings for 'Audio Streaming' option

### PR DESCRIPTION
**Pull request by Mrdabup**
This is a draft for a pull request, to re-add the missing 'Setting.Audio.*' strings in the 'Audio Streaming' menu. Any contribution is welcomed

### CODE REVIEW

**Comment by stiefeljackal** [comment]
You should not be updating the names of the following keys:

* `Settings.AudioInputDeviceSettings`
* `Settings.AudioOutputDeviceSettings`
* `Settings.AudioVolumeSettings`
* `Settings.AudioAccessibilitySettings`
* `Settings.AudioInputFilteringSettings`

Those key names are being used for the new Settings UI and are more than likely key names that the Resonite team will keep. Their updated names are not being used for the Audio Streaming dialog anyway, so there is not point to updating their names.

**Comment by Mrdabup** [comment]
> The following names should not be updated:
> 
>     * `Settings.AudioInputDeviceSettings`
> 
>     * `Settings.AudioOutputDeviceSettings`
> 
>     * `Settings.AudioVolumeSettings`
> 
>     * `Settings.AudioAccessibilitySettings`
> 
>     * `Settings.AudioInputFilteringSettings`
> 
> 
> Those key names are being used for the new Settings UI and are more than likely key names that the Resonite team will keep. Their updated names are not being used for the Audio Streaming dialog anyway, so there is no point to updating their names.
> 
> There is also `Settings.Audio.InputDevice` that is missing as well.
> 
> If you would like, I can go ahead and update these.

Hey thanks for the heads up, I believe that en.json is good to go. I'll keep in mind not to update the strings mentioned. Thanks.

**Comment by stiefeljackal** [comment]
No problem! It looks like all keys are accounted for.

**Comment by Banane9** [comment]
Same as for #391: If they had translations in other languages, it would make sense to restore those in this PR too, as otherwise the linked issues will be closed by merging this PR without the problem being fixed for the other languages (if #241 gets added to the main description).

**Comment by Mrdabup** [comment]
I know this isn't all of them (most likely, I'll do a separate pull request), but I'll let this PR request be able to merge with main for now.

**Comment by Mrdabup** [comment]
Hey @Frooxius , thanks for the message! I've closed the pull request. However, I feel like there should be some kind of clarification on which strings to translate and those not to bring back from the grave.

**Pull request closed without merging**
