### PR TITLE
feat(discord): add discord rich presence strings

### PR DESCRIPTION
**Pull request by ProbablePrime**
See: https://github.com/Frooxius/FrooxEngine/pull/539

### CODE REVIEW

**Comment by Frooxius** [comment]
Hmm... I wonder if this is the right place to put the locale strings. This means if you have your Resonite language set to different language, then your Discord status will be that language for everyone, which might not be desirable.

Does Discord have any localization system on their end? Do we send them the raw strings to display?

**Comment by ProbablePrime** [comment]
@Frooxius you have good points, I meant to comment with some research I did but I forgot.

Discord only allows us to send raw strings, we cannot localize them once they have reached Discord. Due to this I think the best approach is this one, which is to send the strings in the user's locale. You can read more info here: https://discord.com/developers/docs/game-sdk/activities

**Comment by ProbablePrime** [comment]
As some users already provided Strings for this, which was causing CI issues I have removed those from main and moved them to my PR. This preserves them but ensures that they don't get merged in if for whatever reason these strings are rejected.

**Comment by Frooxius** [comment]
Ok I'm merging this in then. Thanks!

**Pull request merged**
