### PR TITLE
Czech translations to error description for registration/login

### PR DESCRIPTION
**Pull request by Chundelac**
Czech translations for strings introduced in #79

### CODE REVIEW

**Comment by rampa3** [comment]
I think our pulls are now in conflict. (My pull: https://github.com/Yellow-Dog-Man/Locale/pull/97) To prevent this into the future, please use the Czech locale coordination issue: https://github.com/Yellow-Dog-Man/Locale/issues/35

**Comment by Chundelac** [comment]
Ok I didn't see the coordination issue my bad 👍 
I created the translation two days ago when these strings are added. How do you want to solve the merge conflict?
We can let this get merged and then solve the conflict in your pull if you want.

**Comment by rampa3** [comment]
Well, I would say let's read both versions and pick the better one. Mine might not be the best, I just try to keep consistent translation style, since I did majority of the locale before launch. If you think yours looks better, I will close my PR, hard reset my fork and do only the teleporter and typo...

**Comment by Chundelac** [comment]
I tried to follow the style that was already there established by you to keep the form as similar as possible while keeping the same information as was in the original English text.
I am sorry I made you do additional work due to not coordinating properly.

**Comment by Chundelac** [comment]
Is there an easy way to compare the two pull requests and maybe pick the changes inside github?
Also would you like to get connected over discord so we can solve this easier?

**Comment by rampa3** [comment]
> I am sorry I made you do additional work due to not coordinating properly.

No problem - I do translations as my way to keep my English skills sharp. For me it is not extra work, but more practice. Reason we have to solve this is to not mess up the merge for Frooxius or Prime, depending on who merges it at the moment.

**Comment by rampa3** [comment]
Also if you want to connect over Discord, feel free - my username is same as GH, but underscore before 3.

**Comment by Frooxius** [comment]
I'm merging this one as the other one is in draft, thank you for the update!

**Comment by rampa3** [comment]
> I'm merging this one as the other one is in draft, thank you for the update!

Mine was retracted to draft after agreeing on that to solve the conflicting translations and is now closed.

**Pull request merged**
