### PR TITLE
th: skeleton file for thai language

### LINKED ISSUE #338: Thai [th]
Requesting Thai to be added to the language list
Skeleton file: #345

### PR DESCRIPTION
**Pull request by xhayper**
Closes #338

### CODE REVIEW

**Comment by Frooxius** [comment]
Is this ready to be merged? It's marked as draft, so I haven't touched it yet. 

The way languages are added to the list is simply by just adding the new language file, so merging this in will do that.

**Comment by xhayper** [comment]
Skeleton file is ready for merging, i have been busy recently due to school so i havent been adding that much translation.

**Comment by Frooxius** [comment]
Sweet thank you! Merging in!

**Comment by xhayper** [comment]
By the way, you guys need to add thai unicode support to the game.
Range is 'U+0E00-U+0E7F'.

**Comment by ProbablePrime** [comment]
We're working on it, thanks!

**Pull request merged**
