### PR TITLE
en.json: added support url

### PR DESCRIPTION
**Pull request by Muppeq**
PR for issue #91

### CODE REVIEW

**Review by ProbablePrime — APPROVED** [review]
Thank you!

**Comment by Frooxius** [comment]
We generally shouldn't bake any URL's or name of the platform into the locale itself as they can change. We'll have to make changes on the code end, to provide the URL as a variable. 

@ProbablePrime Would you be able to handle that?

**Comment by ProbablePrime** [comment]
Ahh yeah I'll get them updated.

**Comment by ProbablePrime** [comment]
@Muppeq I've added your commit to my pr here: https://github.com/Yellow-Dog-Man/Locale/pull/106 that convers these urls to use parameters as Froox requested above.

Doing this keeps your credit of touching them :)

But due to this I'll be closing this one.

**Pull request closed without merging**
