### PR TITLE
Rework and update Dutch (NL) translation

### PR DESCRIPTION
**Pull request by coolymike**
This is a (draft) PR to completely rework and update the Dutch locale.

The translation currently in the upstream repository was made by directly copy-pasting output from several translator programs, which results in many grammatical, spelling, context and inconsistency errors.

The `nl.json` file in this PR includes "comments" marked like `// TODO (word1, word2)`. These "TODO"s exist to mark a word or sentence as "needs proper/consistent translation or needs further discussion".
Many of these are marked TODO to discuss a consistent translation, like "equip". As of starting this PR, 338 lines are marked as "TODO".

The `Store/nl` directory should be as good as finished, but as all other parts of this PR, is still up for discussion.

If there's a single specific line you'd want to discuss, please use the [GitHub code commenting](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request) feature.

### CODE REVIEW

**Comment by coolymike** [comment]
This PR is now ready to merge.

**Comment by coolymike** [comment]
Just noting that this PR is ready for merge

**Comment by Frooxius** [comment]
Ooop, sorry! I forgot about this >///> I'm merging this now, it'll be out in the next build!

**Comment by Frooxius** [comment]
Thank you for the big overhaul!

**Pull request merged**
