### PR TITLE
Ukrainian Patch 1

### PR DESCRIPTION
**Pull request by Antonneposeda**
Please tell me if I did a mistake.

### CODE REVIEW

**Comment by ProbablePrime** [comment]
This looks good, keep it up!

**Comment by jae1911** [comment]
Small thing: make sure the last line is `"Dummy": "Dummy"`, like shown in the `en.json`: https://github.com/Yellow-Dog-Man/Locale/blob/main/en.json#L2720C5-L2720C25

**Comment by Frooxius** [comment]
Thank you very much for adding Ukrainian language! I'm always excited when we get new languages!

I was low-key hoping for someone to do Ukrainian translation specifically at some point. I don't speak the language, but my grandma was from Ukraine.

**Comment by Frooxius** [comment]
Just a small note, the [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) code was wrong. Ukrainian is `uk` instead of `ua`.

I've fixed it on master now, make sure to sync up and make further edits to `uk.json` file instead.

**Pull request merged**
