### PR TITLE
fix: add missing keys for FBT and avatar calibration dialog

### LINKED ISSUE #270: Height Locale Strings Removed, But Still Used for `Full Body / Avatar Calibration`
The `Settings.Height`, `Settings.Metric`, and `Settings.Imperial` locale keys were removed due to the transition from the old to the new settings Screen. However, these keys are still used for Full Body / Avatar Calibration.

image

### PR DESCRIPTION
**Pull request by stiefeljackal**
This will add the missing keys `Settings.Height`, `Settings.Metric`, and `Settings.Imperial` that were removed during the transition from the old Settings screen to the new Settings screen. These keys are still used today for the Full Body / Avatar Calibration dialog that was reported in #270.

If new key names will be given to them, then I can update accordingly.

This fixes #270.
This fixes https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2279.

### CODE REVIEW

**Comment by stiefeljackal** [comment]
This will fix #270.
This will fix https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2279.

**Comment by Banane9** [comment]
If they had translations in other languages, it would make sense to restore those in this PR too, as otherwise the linked issues will be closed by merging this PR without the problem being fixed for the other languages.

**Comment by stiefeljackal** [comment]
> If they had translations in other languages, it would make sense to restore those in this PR too, as otherwise the linked issues will be closed by merging this PR without the problem being fixed for the other languages.

Makes sense. Restoring the previous keys from an earlier commit should be fine, so I will do that later today.

**Comment by Banane9** [comment]
> Makes sense. Restoring the previous keys from an earlier commit should be fine, so I will do that later today.

That'd be perfect 👍

**Comment by stiefeljackal** [comment]
Added missing keys for other locales based on a previous commit (https://github.com/Yellow-Dog-Man/Locale/tree/25ce3868d90dc53dd7cedf8bc16b6b2d794e6a62). These values were from previous translators, so this should be okay.

**Comment by stiefeljackal** [comment]
Messed up the rebase, so I will close this PR for now. Existing keys might be used, so these legacy keys won't be included. I will create a new PR at a later point to fill in the values for `General.Units.Metric` and `General.Units.Imperial` with the same values from `Settings.Metric` and `Settings.Imperial` (minus the unit mentioned) for those locales that previously had them under the legacy keys but now missing.

**Pull request closed without merging**
