### PR TITLE
FR: New setting strings + filters

### PR DESCRIPTION
**Pull request by jae1911**
Adds:
- New filter
- New setting strings for Steam Voice

### CODE REVIEW

**Comment by Frooxius** [comment]
This unfortunately conflicts with the other changes right now, I don't know which ones to keep.

**Comment by jae1911** [comment]
Let me resolve that really quickly.

**Comment by Frooxius** [comment]
Ok! I just need to have the conflict resolved, don't worry about the checks.

**Comment by jae1911** [comment]
There you go, should be good to go!

**Comment by Frooxius** [comment]
Sweet thank you! Merging!

**Pull request merged**
