### PR TITLE
zh-cn:Add more keys.

### PR DESCRIPTION
**Pull request by modimobeikete**
Due to some keys from other languages has been influenced, I decided to delete some keys to make sure the check is success

### CODE REVIEW

**Comment by modimobeikete** [comment]
I hope this delay is because you're quite busy instead of inactive to it.

**Comment by shadowpanther** [comment]
Hey, @modimobeikete, you changed other language files as part of your PR, but that would cause conflicts in others' PRs. Please don't do this. My https://github.com/Yellow-Dog-Man/Locale/pull/331 already addresses this key name change in a better way.

Last time someone did that, my PR was not accepted at all, and I had to do a manual merge to fix the conflict properly.

You don't have to get a green checkmark for your PR to get accepted. Please don't try to fix everything at once.

**Comment by Frooxius** [comment]
Like @shadowpanther mentioned, you should avoid modifying the other locales.

This PR now conflicts as a result, so we can't merge it.

**Comment by Frooxius** [comment]
Actually the conflicts were just empty lines, so I managed to resolve them myself. Merging this in, thanks!

**Pull request merged**
