### PR TITLE
feat(cursors): cursor settings

### PR DESCRIPTION
**Pull request by ProbablePrime**

### CODE REVIEW

**Comment by ProbablePrime** [comment]
Note so I dont forget, gonna double check the output of this shortly.

**Comment by ProbablePrime** [comment]
I checked it, looks good. Didn't take long but hey I thought it would take longer :D

**Comment by ProbablePrime** [comment]
https://github.com/Yellow-Dog-Man/FrooxEngine/pull/838/ for the code changes

**Comment by Frooxius** [comment]
Merging this now! Thank you!

**Pull request merged**
