### PR TITLE
zh-cn:Polish purely machine translated locales

### PR DESCRIPTION
**Pull request by modimobeikete**
I checked some translation and here is why I decided to change it
Line 43,44,45:“启停，键入” are not what native Chinese player will say.
Line  77,78：“消灭” has lots of meaning,but the main meaning is Eliminate.And it's same to 克隆.It means clone.
Line 137:In Chinese social games,we usually say 好友 to describe friends who is playing in this game.
Line 165,186,200.201:It's really hard to convey host and session.But by reviewing my experience on hosting the game,I found it they get used to saying 房主 as a host.Here is a picture to show how they start session to play the game.
QQ截图20240405180807

Line 181:To telling the truth,I have no idea what“套接字” means.The original words steam networking sockets is probably means connection between steam server.So I think 网络通讯 is easier to understand.
Line 209:I think mobile in this locale is means a platform.
Line 277:If I do want to translate out of,we say x到x,but in here,This locale wants to convey each session's numbers of people.So I decide to use / as out of
Line 474:Appraently this is not what the proper translation,it's likely a machine translation.
Line 535:“销毁” words doesn't sync to the Line 77,78
Line 1944:As a resonite user,I know this is a script tool.But for the new player,they don't understand what ProtoFlux means.So I think adding a script is easier to undetstand.
Here is all of why I change it.Please tell me if there's any confused question above.

### CODE REVIEW

**Comment by modimobeikete** [comment]
If is possible,can I enter the translator list?

**Comment by modimobeikete** [comment]
Why does this process takes too much time on checking?Please don't hesitate to tell me what's wrong.

**Comment by modimobeikete** [comment]
Is someone can check this pull request?Please let me know if there's any problems with it so that I can adjust it.

**Comment by Frooxius** [comment]
Thank you very much for the contribution! Merging this in!

**Pull request merged**
