### PR TITLE
Added tooltip name locales

### PR DESCRIPTION
**Pull request by RueShejn**

### CODE REVIEW

**Comment by Frooxius** [comment]
Merging those in, thanks!

**Comment by coolymike** [comment]
What's the purpose of this PR? Almost all the strings added in this PR are already available under `Tools.Names.{ToolName}`.

<details>
<summary>Keys starting with <code>Tools.Names.</code> in en.json:</summary>
<pre>
{
  "Tools.Names.MultiTool": "Multi-Tool",
  "Tools.Names.CommonTools": "Common Tools",
  "Tools.Names.ManipulationTools": "Manipulation Tools",
  "Tools.Names.InformationTools": "Information Tools",
  "Tools.Names.GeometryLineBrush": "Geometry Line Brush Tool",
  "Tools.Names.Developer": "Developer Tool",
  "Tools.Names.ComponentClone": "Component Clone Tool",
  "Tools.Names.ProtoFlux": "ProtoFlux Tool",
  "Tools.Names.Material": "Material Tool",
  "Tools.Names.Glue": "Glue Tool",
  "Tools.Names.Light": "Light Tool",
  "Tools.Names.Shape": "Shape Tool",
  "Tools.Names.Microphone": "Microphone Tool",
  "Tools.Names.GrabbableSetter": "Grabbable Setter Tool",
  "Tools.Names.PhysicalColliderSetter": "Physical Collider Setter Tool",
  "Tools.Names.MeshVisibility": "Mesh Visibility Tool",
  "Tools.Names.CameraObjectVisibility": "Camera Object Visibility Tool",
  "Tools.Names.Color": "Color Tool",
  "Tools.Names.Mesh": "Mesh Tool",
  "Tools.Names.RiggedMeshTransfer": "Rigged Mesh Transfer Tool",
  "Tools.Names.Slicer": "Mesh Slicer Tool",
  "Tools.Names.ControllerDiagnostic": "Controller Diagnostic Tool",
  "Tools.Names.Measure": "Measure Tool",
  "Tools.Names.Label": "Label Tool"
}</pre></details>

<details>
<summary>Keys starting with <code>Tooltip.</code> and ending with <code>.Name</code> (now) in en.json:</summary>
<pre>
{
  "Tooltip.GeometryLineBrush.Name": "Geometry Line Brush",
  "Tooltip.Color.Name": "Color Tool",
  "Tooltip.GrabbableSetter.Name": "Grabbable Setter Tool",
  "Tooltip.CharacterCollider.Name": "Character Collider Setter Tool",
  "Tooltip.Light.Name": "Light Tool",
  "Tooltip.MeshVisibility.Name": "Mesh Visibility Tool",
  "Tooltip.Mesh.Name": "Mesh Tool",
  "Tooltip.Slicer.Name": "Object Slicer Tool",
  "Tooltip.Material.Name": "Material Tool",
  "Tooltip.Microphone.Name": "Microphone",
  "Tooltip.ProtoFlux.Name": "Proto-Flux Tool",
  "Tooltip.Meter.Name": "Meter Tool",
  "Tooltip.Glue.Name": "Glue Tool",
  "Tooltip.RigTransfer.Name": "Rig Mesh Transfer Tool",
  "Tooltip.ComponentClone.Name": "Component Clone Tool",
  "Tooltip.Shape.Name": "Shape Tool",
  "Tooltip.CameraObjectHider.Name": "Camera Object Hider Tool",
  "Tooltip.ControllerDiagnostic.Name": "Controller Diagnostic Tool",
  "Tooltip.Labeler.Name": "Labeler Tool"
}
</pre></details>

<details>
<summary>(Sorted) diff between those two, <code>&lt;</code> exists as <code>Tools.Names.{ToolName}</code>, <code>&gt;</code> exists as <code>Tooltip.{ToolName}.Name</code></summary>
<pre>
1c1,2
<  "Camera Object Visibility Tool",
---
>  "Camera Object Hider Tool",
>  "Character Collider Setter Tool",
3d3
<  "Common Tools",
6,7c6
<  "Developer Tool",
<  "Geometry Line Brush Tool",
---
>  "Geometry Line Brush",
10,11c9
<  "Information Tools",
<  "Label Tool"
---
>  "Labeler Tool"
13d10
<  "Manipulation Tools",
15,16d11
<  "Measure Tool",
<  "Mesh Slicer Tool",
19,23c14,18
<  "Microphone Tool",
<  "Multi-Tool",
<  "Physical Collider Setter Tool",
<  "ProtoFlux Tool",
<  "Rigged Mesh Transfer Tool",
---
>  "Meter Tool",
>  "Microphone",
>  "Object Slicer Tool",
>  "Proto-Flux Tool",
>  "Rig Mesh Transfer Tool",
</pre></details>

Some names differ slightly, for example `Physical Collider Setter Tool` becoming `Character Collider Setter Tool`, and `Mesh Slicer Tool` becoming `Object Slicer Tool`. That aside, these keys would serve the same purpose as the already existing `Tools.Names.{ToolName}`, which could lead to inconsistent naming of tools.

**Comment by ProbablePrime** [comment]
I think there's a mixup here. tagging @RueShejn and @Frooxius .

Once this mixup is resolved and in the future, I'll see about doing a batch operation to rename tooltip to tool or something like that.

**Comment by coolymike** [comment]
I have created a new issue for this discussion, so it doesn't go unseen in the closed PRs.

#563

**Pull request merged**
