### PR TITLE
More polishing, removed English words and fixed technical strings

### PR DESCRIPTION
**Pull request by FoxoBread**
I'm getting some feedback from folks about the more technical and missing strings, next commit should address those.
Hopefully I've not made some structure blunders either 😅

Working on store description(s) at the moment, those should also be in the next commit or the one after :D

### CODE REVIEW

**Comment by FoxoBread** [comment]
Ah, I do now spot PR #113 opened by [AdamK2003](https://github.com/AdamK2003)

That's a slight doozy

**Comment by FoxoBread** [comment]
And I also failed to see #109 by @Alex-2Pi 

Nightmare really 😦

**Comment by Alex-2Pi** [comment]
I see that too, that's what brought us together to add it at a similar time 😅

**Comment by ProbablePrime** [comment]
I am testing something one moment.

**Comment by Frooxius** [comment]
Thank you, merging in!

**Pull request merged**
