### PR TITLE
Updated PL.json,  Some of the missing keys have been added with translation

### PR DESCRIPTION
**Pull request by Alex-2Pi**
My apologies if the number of translations I have completed is considered insufficient, but at this moment, I would like to upload what I have so that no one has to repeat this effort in vain.

I am uncertain if my alphabetical file sorting was the most optimal choice.
Ah, I also added myself to the list of individuals who have made modifications to this translation.

### CODE REVIEW

**Comment by ProbablePrime** [comment]
Thank you but yes, please don't sort the file alphabetically. The ordering we have is loosely based on "areas" or "parts of resonite"

**Review by ProbablePrime — CHANGES_REQUESTED** [review]
We'll need this to return to the "area" based sorting, I think the python file in this repo can do that.

**Comment by Alex-2Pi** [comment]
From what I see and how I understand it, my change here has already been added to this request.

**Comment by ProbablePrime** [comment]
Yes, Much better. I'll be processing these soon.

**Comment by Frooxius** [comment]
Thank you, merged in!

**Pull request merged**
