### PR TITLE
Add key

### LINKED ISSUE #155: Missed "Contacts.NoSession" translation key
For current moment (at commit e8c2eda93a85da6980e1272f117bf729f6d96f8c) in en locale don't contains "Contacts.NoSession" translation key

I noticed that this was missing when user don't have open any worlds (only Userspace world)
Resonite_2gu455gxFq

### PR DESCRIPTION
**Pull request by 989onan**
Fix #155 . I'd figure this wouldn't hurt to at least attempt to fix it

### CODE REVIEW

**Review by ProbablePrime — APPROVED** [review]

**Comment by ProbablePrime** [comment]
If you rebase this it'll pass the CI.

You're quite right to add the key, if for some reason a contact update is sent without a session this will be displayed.

**Comment by Frooxius** [comment]
This is a good catch, but the text is a bit too verbose, adding unnecessary terms.

This should generally as short as possible, so it's quick to read and fits in the space.

E..g. something like "No session", "Not in any session", "No session active".

**Comment by LeoCatsune** [comment]
Bumping this since it hasn't been touched in a while and still remains waiting changes? Obviously this is a bit of an edge case but probably best not to leave any keys out (especially since they're not being counted in the baseline)

**Comment by Frooxius** [comment]
If it's waiting on changes - it means changes need to be done by author of the PR. Since they haven't done these, we can't do anything with this PR.

I can just close this and write our own key for this since it's just a small one.

**Comment by 989onan** [comment]
this seems like a better idea, thanks!

**Pull request closed without merging**
